import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Link href="/grid">Grid</Link>
        <br />
        <Link href="/bar">Bar</Link>
        <br />
        <Link href="/doughnut">Doughnut</Link>
        <br />
        <Link href="/line">Line</Link>
        <br />
        <Link href="/tree">Tree</Link>
        <br />
        <Link href="/financial">Financial</Link>
        <br />
        <Link href="/range">Range</Link>
        <br />
        <Link href="/">Home</Link>
        <br />
        {children}
      </body>
    </html>
  );
}
